services:
  db:
    image: postgres:16-alpine
    container_name: gymmawy-db
    restart: always
    environment:
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: gymmawy
      POSTGRES_SUPERUSER: true
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
