services:
  db:
    image: postgres:16-alpine
    container_name: gymmawy-db
    restart: always
    environment:
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: gymmawy
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data:
